nelmio_cors:
  defaults:
    allow_origin: ['https://book.d3v.eu']
    allow_credentials: false
    allow_headers: ['Content-Type']
    allow_methods: ['POST', 'GET', 'OPTIONS']
    max_age: 3600
  paths:
    '^/':
      origin_regex: false