nelmio_cors:
  defaults:
    allow_origin: ['%env(regex:CORS_ALLOW_ORIGIN)%']
    allow_methods: ['GET', 'POST', 'OPTIONS']
    allow_headers: ['Content-Type']
    max_age: 3600
  paths:
    '^/':
      allow_origin: ['%env(regex:CORS_ALLOW_ORIGIN)%']
      allow_methods: ['GET', 'POST', 'OPTIONS']
      allow_headers: ['Content-Type']
      max_age: 3600