nelmio_cors:
  defaults:
    allow_origin: ['https://book.d3v.eu', 'http://localhost:8787']
    allow_methods: ['POST', 'GET', 'OPTIONS']
    allow_headers: ['Content-Type']
    max_age: 3600
  paths:
    '^/': # lub '^/subscribe$' jeśli chcesz tylko dla tej ścieżki
    allow_origin: ['https://book.d3v.eu', 'http://localhost:8787']
    allow_methods: ['POST', 'GET', 'OPTIONS']
    allow_headers: ['Content-Type']
    max_age: 3600